development:
  dialect: postgres
  database: toodo_development
  user: isrealdeep
  password: Tajasdad1908!
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://isrealdeep:Tajasdad1908!@127.0.0.1:5432/toodo_test?sslmode=enable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://isrealdeep:Tajasdad1908!@127.0.0.1:5432/toodo_production?sslmode=enable"}}
